### ISSUE TITLE
support for PHP 8.0

### ISSUE THREAD

**Issue by jmckenna** [dvzgeo/php_ogr#11]
- some hints of changes needed:
  - similar change for `ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX` as https://github.com/ejn/php_ogr/commit/cf9a331185ca9e2f76a51b297681f2d0d66fea99
  - handle removal of `TSRMLS_DC`, in ogr.c (or just declare these missing macros as https://www.seidengroup.com/2020/12/07/porting-extensions-to-php-8/ )
  ...

(all Windows builds for MapServer will be moving to PHP8, it would be nice to package php_ogr with it)

**Comment by ejn** [comment]
@jmckenna I've just opened a WIP PR for PHP8.0 support: #14. If you're still on GDAL 2.x for MS4W then you should be good to go with that. If you've also updated to GDAL 3 then I've got a WIP branch for that which I'll push a.s.a.p.: Compilation is already working, but the PHPUnit tests need a little work to update the expected results.

**Comment by jmckenna** [comment]
@ejn understood, I'm working on an MS4W release that has GDAL 3.4.0, PHP8, so I'll test your branches with that, today.  thanks!

**Comment by jmckenna** [comment]
@ejn sorry for my delay, I had to upgrade more of the build first.  But good news, I applied #14 & #15 and things are working in MS4W (with PHP 8.0.12 and GDAL 3.4.0).  (!!)    I honestly don't usually run the unit tests, but let me know if you want me to set them up here.    And thanks for this!! 🚀

**Comment by ejn** [comment]
Thanks for testing @jmckenna! Since the unit tests now work for me (TM) then I'll assume everything is good and start merging.

**Comment by ejn** [comment]
Closed with #14

**Comment by ejn** [comment]
I've tagged [Release 1.6.0](https://github.com/dvzgeo/php_ogr/releases/tag/1.6.0) with all the changes in so that you can reference a version number for MS4W.

**Comment by jmckenna** [comment]
@ejn perfect, thanks so much!!!!
