### ISSUE TITLE
Support for GDAL 3

### ISSUE THREAD

**Issue by ejn** [dvzgeo/php_ogr#12]
Whilst working on #11 it is also apparent that some changes are necessary to support GDAL 3.

Functions removed in OSR API:
 * `OSR_FixupOrdering()`
 * `OSR_Fixup()`
 * `OSR_StripCTParms()`

Additionally, results for the PHPUnit-Tests must be updated, particularly w.r.t. coordinate axis order handling.

**Comment by jmckenna** [comment]
excellent point!  (GDAL 3.4.0 is the goal)

**Comment by ejn** [comment]
@jmckenna With all 4 open PR applied I can now compile and run the unit tests on both PHP 7.3 with GDAL 2.4 and PHP 8.0 with GDAL 3.0.

Let me know how you get on! If it all works for you then I'll merge everything and tag a release.

**Comment by ejn** [comment]
Closed with #15
