### ISSUE TITLE
[feature request] add version to phpinfo

### ISSUE THREAD

**Issue by jmckenna** [dvzgeo/php_ogr#19]
Something like the following in `ogr.c` but I don't know how to get the version number elegantly...

```
    php_info_print_table_start();
    php_info_print_table_header(2, "ogr support", "enabled");
    php_info_print_table_row(2, "Version", "1.6.0");
    php_info_print_table_row(2, "GDAL Version", "GDAL 3.4.0, released 2021-11-04");
    php_info_print_table_end();
```

**Comment by ejn** [comment]
Good idea. Ideally the GDAL/OGR version should probably also be shown, which is easier. I'll look into it when I have a quiet few minutes.

**Comment by jmckenna** [comment]
Great point about including GDAL version also!

**Comment by ejn** [comment]
Finally found half an hour to get this sorted. Let me know if it causes problems and thanks for the great suggestion!
